# name of workflow
name: Maven CI

# events that trigger workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21.0.7
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.7'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven Tests
        run: mvn clean test
  